### ISSUE TITLE
As a registered user, I want to be able to accurately see emergency contact responses to my alert so I know help is on the way or instructions to follow.

### ISSUE THREAD

**Issue by sahajm99** [HemaTummapala/SWE_Faster_Emergency_Care_during_Accidents#8]
Estimation of efforts: 2-3 weeks

Acceptance criteria : Upon emergency contacts receiving the alert, Users shall also receive a notification stating that the emergency contacts have been notified and can look into the tracking details.

**Comment by HemaTummapala** [comment]
Emergency contacts are receiving the alerts and the same acknowledgement is given to the user
